name: Editor Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Docker Login
      run: docker login -u="${{ secrets.DOCKERLOGIN}}" -p="${{ secrets.DOCKERPASSWORD }}"
    - name: Build the Docker image
      working-directory: WebApps/Editor/Cosmos.Editor
      run: docker build . -t cosmos-editor:latest
    - name: Push container to Docker Hub
      run: docker push ${{ secrets.DOCKERLOGIN}}/cosmos-editor
